{
 "title": "Server Browser",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Server",
    "label": "Server",
    "query": {
     "query": "query_result(count(interface_oper_state{remote_role=\"server\"}) by (remote_device))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Switch Side Oper Status",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "interface_oper_state{remote_device=\"$Server\"}",
     "legendFormat": "{{device}}  {{interface_name}}"
    }
   ]
  },
  {
   "title": "Carrier Transitions over 10s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "changes(interface_statistics_carrier_transitions{remote_role=\"server\", remote_device=\"s8\"}[10s])",
     "legendFormat": "{{device}} {{interface_name}} -> {{remote_device}} {{remote_interface}} "
    }
   ]
  },
  {
   "title": "FCS errors over time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "rate(interface_statistics_in_fcs_error_packets{remote_device=\"$Server\"}[10s])",
     "legendFormat": "{{device}} {{interface_name}}"
    }
   ]
  },
  {
   "title": "Switch side traffic in/out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "interface_traffic_rate_in_bps{remote_device=\"$Server\"}",
     "legendFormat": "{{device}} {{interface_name}} rx <- {{remote_interface}} $Server in"
    },
    {
     "expr": "interface_traffic_rate_out_bps{remote_device=\"$Server\"}",
     "legendFormat": "{{device}} {{interface_name}} tx -> {{remote_interface}} $Server"
    }
   ]
  }
 ]
}